FROM python:3.9

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

#command to run the Celery worker
CMD ["celery", "-A", "my_goals_project", "worker", "--loglevel=info"]
