version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"    # External access for apps running outside Docker
      - "9093:9093"    # Internal access for Docker containers
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .  # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile.celery  # Specify the new Dockerfile name
    volumes:
      - .:/app  # Optional: If you need the project files
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093  # Internal Docker access
      - REDIS=redis

