global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']
      
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']