# Generated by Django 4.2.16 on 2024-09-15 10:40

from django.db import migrations, models
import my_goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0004_goal_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_date',
            field=models.DateField(default=my_goals.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=my_goals.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_date',
            field=models.DateField(default=my_goals.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateField(default=my_goals.models.get_current_date),
        ),
    ]
