# Generated by Django 4.2.16 on 2024-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0005_alter_goal_created_date_alter_goal_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
    ]
