# Generated by Django 4.2.16 on 2024-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0006_goal_is_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
