# Generated by Django 4.2.16 on 2024-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0007_alter_goal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
