# Generated by Django 4.2.16 on 2024-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0008_subtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
