# Generated by Django 4.2.16 on 2024-09-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0009_goal_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
    ]
