# Generated by Django 4.2.16 on 2024-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0010_remove_goal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
