# Generated by Django 4.2.16 on 2024-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0011_goal_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
