# Generated by Django 4.2.16 on 2024-09-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_goals', '0012_subtask_completed_date'),
    ]
    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
